namespace DemoNamespace
{
  [IS_DEMO_INTERFACE]
  interface IDemoInterface
  {
    void DoSomething();
  }
  
  interface IDemoInterface2 requires IDemoInterface, IGreatDemoInterface
  {
    void DoSomething();
  }
  
  runtimeclass DemoClass : [PREVIEW_API] /* comment */ IDemoInterface
  {
    void DoSomething();
  }
  
  runtimeclass DemoClass2 : IDemoInterface, /* comment */ [PREVIEW_API] IGreatDemoInterface
  {
    void DoSomething();
  }
}
